version: '3.3'

volumes:
  db_data:
  wordpress_data:

services:
  db:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=wordpress-user
      - MARIADB_DATABASE=wordpress-pass
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - net

  wordpress:
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - wordpress_data:/bitnami
    networks:
      - net
    depends_on:
      - db

networks:
  net: 
